### ISSUE TITLE
Cannot start the IOS simulator

### ISSUE THREAD

**Issue by hurricaney7** [mmcc007/screenshots#169]
Once I run screenshots in the root of my Flutter project, I got the following error.

tarting flutter daemon...                                          0.6s
Clearing images in ios/fastlane/screenshots/en-US for 'iPhone X'...

Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/zexinwan/Library/Developer/CoreSimulator/Devices/9A63E188-
B6D6-4636-BE31-7F4D20852F11/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:361:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:178:19)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:226:40)
<asynchronous suspension>
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:153:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:152:18)
<asynchronous suspension>
#11     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#12     screenshots (package:screenshots/src/run.dart:47:12)
<asynchronous suspension>
#13     main (file:///Users/zexinwan/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

It usually appears after failed launching of an IOS simulator

**Comment by mmcc007** [comment]
This has been fixed in master (not yet released). To install:
```
pub global activate -s git https://github.com/mmcc007/screenshots.git
```

Let me know how it goes.

**Comment by olheimer** [comment]
I'm getting the same issue still after switching to master as described.

**Comment by mmcc007** [comment]
@olheimer Try running with the -v option to get more detail and provide output. Also, include the output of `flutter doctor -v`

**Comment by just-kip** [comment]
Same issue on master branch
```
Starting flutter daemon...                                          5.8s
Warning: using default value 'phone' in fastlane directory.
Clearing images in ios/fastlane/screenshots/en-US for 'iPhone 11'...
Warning: using default value 'phone' in fastlane directory.
Clearing images in ios/fastlane/screenshots/en-US for 'iPhone 8'...
Starting iPhone 11...
Running --target=test_driver/screenshots.main.g.dart --driver=test_driver/screenshots.test.g.dart on 'iPhone 11' in locale en-US with flavor dev...
Starting application: test_driver/screenshots.main.g.dart
Running pod install...                                              3.1s
Running Xcode build...                                          
Xcode build done.                                           15.7s
	path: satisfied (Path is satisfied), interface: en0
Configuring the default Firebase app...
6.12.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
	path: satisfied (Path is satisfied), interface: en0
6.12.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60105000 started
6.12.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
flutter: Observatory listening on http://127.0.0.1:54923/mFDnp3edcqw=/
	path: satisfied (Path is satisfied), interface: en0
6.12.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
Configured the default Firebase app __FIRAPP_DEFAULT.
00:00 +0: screenshotTests (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:54923/mFDnp3edcqw=/
[trace] FlutterDriver: Isolate found with number: 448132436537355
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:00 +0: screenshotTests moreLoggedIn
Screenshot moreLoggedIn created
00:02 +1: screenshotTests moreLoggedOut
Screenshot moreLoggedOut created
00:04 +2: screenshotTests (tearDownAll)
00:04 +2: All tests passed!
Stopping application instance.
Warning: 'iPhone 11' images will not be processed
Warning: using default value 'phone' in fastlane directory.
Moving screenshots to screenshots/ios/fastlane/screenshots/en-US
/Users/kg/Library/Developer/CoreSimulator/Devices/0FA16B8A-11FD-4BD2-9569-469CA8FE6BC2/data/Library/Preferences/.GlobalPreferences.plist: invalid object in plist for destination format


Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/kg/Library/Developer/CoreSimulator/Devices/0FA16B8A-11FD-4BD2-9569-469CA8FE6BC2/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:427:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:245:7)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:226:40)
<asynchronous suspension>
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:153:18)
<asynchronous suspension>
#11     runInContext (package:screenshots/src/context_runner.dart:17:24)
<asynchronous suspension>
#12     screenshots (package:screenshots/src/run.dart:47:12)
<asynchronous suspension>
#13     main (file:///Users/kg/.pub-cache/git/screenshots-ed88f1a12cafb144c802bc309db7799d15fe626f/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-RU)
    • Flutter version 1.9.1+hotfix.6 at /Users/kg/.flutter_sdk/1.9.1+hotfix.6
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/kg/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/kg/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 • 5C481623-3DD4-4A78-A0C3-CA3B2B156DF0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

**Comment by mmcc007** [comment]
@just-kip Looks like it works for you for iPhone 11 and not for iPhone 8.

Please provide output of
```bash
plutil -convert json -o - /Users/kg/Library/Developer/CoreSimulator/Devices/0FA16B8A-11FD-4BD2-9569-469CA8FE6BC2/data/Library/Preferences/.GlobalPreferences.plist
```
and output of screenshots with -v option.

If not already, try starting and stopping the iPhone 8 simulator.

Note: screenshots [works](https://travis-ci.com/mmcc007/screenshots/jobs/263151351#L2213) with iPhone 11 and Phone 8 simulators on `Xcode 11.2.1, Build version 11B500` (did not try your `Xcode 11.2, Build version 11B52` version). Both simulators used the GlobalPreferences-missing fix.

If problem continues try:
```bash
git clone https://github.com/mmcc007/screenshots
cd screenshots/example
git checkout 169_global_preferences
screenshots -c screenshots_ios.yaml -v

```
and provide output.

**Comment by inboxg9** [comment]
I resolved these issue, per simulator, by

- Keeping only 1 iOS version for that simulator, eg `13.3` and deleting the rest
- Start it once, if you havn't already done so
- Open it, then: Simulator ->Hardware -> Erase content and setting
- Close simulator
- rerun `screenshots`

**Comment by isorensen** [comment]
> I resolved these issue, per simulator, by
> 
> * Keeping only 1 iOS version for that simulator, eg `13.3` and deleting the rest
> * Start it once, if you havn't already done so
> * Open it, then: Simulator ->Hardware -> Erase content and setting
> * Close simulator
> * rerun `screenshots`

I had the same issue, and after Erasing all content and setting from simulator, closing, and running again, fixed the problem.

**Comment by isorensen** [comment]
> > I resolved these issue, per simulator, by
> > 
> > * Keeping only 1 iOS version for that simulator, eg `13.3` and deleting the rest
> > * Start it once, if you havn't already done so
> > * Open it, then: Simulator ->Hardware -> Erase content and setting
> > * Close simulator
> > * rerun `screenshots`
> 
> I had the same issue, and after Erasing all content and setting from simulator, closing, and running again, fixed the problem.

After some days, problem showed up again. Any update on fixing the issue or suggesting another workaround/solution?

@mmcc007 , below is the error message and output of the command that threw the error:
```
~/Documents/iDev.nosync/Credifit/app(feature/9-isorensen) » screenshots
Starting flutter daemon...                                          6.4s
Clearing images in android/fastlane/metadata/android/pt-BR/images/phoneScreenshots for 'Nexus
6P'...
Clearing images in ios/fastlane/screenshots/pt-BR for 'iPhone 8 Plus'...
Warning: using default value 'phone' in fastlane directory.
Clearing images in ios/fastlane/screenshots/pt-BR for 'iPhone 11 Pro Max'...

Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/eduardosorensen/Library/Developer/CoreSimulator/Devices/B4CC7D58-74B8-44A5-B6F0-4CAF2003D23E/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:361:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:178:19)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:226:40)
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#11     runInContext (package:screenshots/src/context_runner.dart:16:24)
#12     screenshots (package:screenshots/src/run.dart:47:12)
#13     main (file:///Applications/flutter/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
---------------------------------------------------------------------------------------------
~/Documents/iDev.nosync/Credifit/app(feature/9-isorensen) » plutil -convert json -o - /Users/eduardosorensen/Library/Developer/CoreSimulator/Devices/B4CC7D58-74B8-44A5-B6F0-4CAF2003D23E/data/Library/Preferences/.GlobalPreferences.plist

/Users/eduardosorensen/Library/Developer/CoreSimulator/Devices/B4CC7D58-74B8-44A5-B6F0-4CAF2003D23E/data/Library/Preferences/.GlobalPreferences.plist: invalid object in plist for destination format
```

**Comment by mmcc007** [comment]
@isorensen plutil apparently does not permit converting to json when a date is present.
https://juzhax.com/2013/12/invalid-object-in-plist-for-destination-format/
So changed to extracting locale using xml.
Give it a try with something like:
```
git clone https://github.com/mmcc007/screenshots
cd screenshots/example
git checkout 169_global_preferences
screenshots -c screenshots_ios.yaml -v
```

**Comment by bartektartanus** [comment]
> @isorensen plutil apparently does not permit converting to json when a date is present.
> https://juzhax.com/2013/12/invalid-object-in-plist-for-destination-format/
> So changed to extracting locale using xml.
> Give it a try with something like:
> 
> ```
> git clone https://github.com/mmcc007/screenshots
> cd screenshots/example
> git checkout 169_global_preferences
> screenshots -c screenshots_ios.yaml -v
> ```

This was not the correct solution for me, as the `screenshot` was already installed from pub, so even after `git clone`, the `screenshot` command ran an old version.
This solution worked for me:
Run this 
```sh
git clone https://github.com/mmcc007/screenshots
cd screenshots
git checkout 169_global_preferences
pub global activate --source path /path/to/repo/screenshots
```
and also add this to `pubspec.yaml`
```yaml
dev_dependencies:
  screenshots: 
    path: /path/to/repo/screenshots
```

**Comment by savy-91** [comment]
I tried following bartektartanus advice but it still does not work for me.

**Comment by zbarryte-luminopia** [comment]
@mmcc007 - I'm still receiving this issue, and it appears to be caused by the `.GlobalPreferences.plist` file not existing for simulators that have not yet been launched.

For simulators on which I've experienced the Issue 169, I've been able to resolve it by opening the simulator for that device and then running the `screenshots` command again; however, this is not ideal for running `screenshots` on CI.

**Comment by zbarryte-luminopia** [comment]
@mmcc007 - When I tried that fix, I still had the issue.

Here is my output after running `screenshots -v` after activating the `169_global_preferences` version:

```
[ +101 ms] Starting flutter daemon...
[  +18 ms] executing: flutter daemon
[+1121 ms] <== Starting device daemon...
[   +7 ms] <== [{"event":"daemon.connected","params":{"version":"0.5.3","pid":10321}}]
[   +4 ms] ==> [{"method":"device.enable","id":0}]
[        ] waiting for response: {method: device.enable, id: 0}
[  +32 ms] <== [{"id":0}]
[+5031 ms] executing: [./] sh -c ios-deploy -c || echo "no attached devices"
[ +134 ms] Starting flutter daemon... (completed in 6.3s)
[   +1 ms] ==> [{"method":"device.getDevices","id":1}]
[        ] waiting for response: {method: device.getDevices, id: 1}
[   +2 ms] <== [{"id":1,"result":[]}]
[   +2 ms] ==> [{"method":"emulator.getEmulators","id":2}]
[        ] waiting for response: {method: emulator.getEmulators, id: 2}
[  +58 ms] <== [{"id":2,"result":[{"id":"Nexus_5X_API_28","name":"Nexus 5X API
28","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","name":"iOS
Simulator","category":"mobile","platformType":"ios"}]}]
[   +9 ms] daemonEmulator=id: Nexus_5X_API_28, name: Nexus 5X API 28, category: mobile, platformType: android
[   +2 ms] daemonEmulator=id: apple_ios_simulator, name: iOS Simulator, category: mobile, platformType: ios
[ +216 ms] executing: [./] xcrun simctl list devices --json
[  +30 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/android-wait-for-emulator
[  +13 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/android-wait-for-emulator-to-stop
[  +15 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/simulator-controller
[  +13 ms] executing: [./] chmod u+x /tmp/screenshots/resources/script/sim_orientation.scpt
[   +9 ms] Warning: using default value 'phone' in fastlane directory.
[        ] Clearing images in ios/fastlane/screenshots/en-US for 'iPad Pro (9.7-inch)'...
[ +228 ms] executing: [./] xcrun simctl list devices --json
[  +29 ms] executing: [./] plutil -convert json -o -
/Users/me/Library/Developer/CoreSimulator/Devices/DB0FBF85-1ADA-44B2-A16C-D2DE264788FB/data/Library/Preferences/.GlobalPrefer
ences.plist
Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/me/Library/Developer/CoreSimulator/Devices/DB0FBF85-1ADA-44B2-A16C-D2DE264788FB/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:361:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:178:19)
#2      Screenshots.runTestsOnAll (package:screenshots/src/run.dart:226:40)
#3      Screenshots.run (package:screenshots/src/run.dart:127:11)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:42:26)
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#11     runInContext (package:screenshots/src/context_runner.dart:16:24)
#12     screenshots (package:screenshots/src/run.dart:41:12)
#13     main (file:///Users/me/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

And here is my output from `flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.12.13+hotfix.7 at /Users/me/Library/Flutter/flutter
    • Framework revision 9f5ff2306b (7 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by mmcc007** [comment]
@zbarryte-luminopia you may have an old version of branch (it should have created a new global preference file). To update branch, try:
```
cd screenshots
git checkout 169_global_preferences
git pull
pub global activate --source path .
```

**Comment by zbarryte-luminopia** [comment]
@mmcc007 - Ah!  It looks I was just having issues with global activation -- so, in fact, the code I was executing was not the code with the fix.  I had previously globally activated `screenshots 2.1.1`, and the cache still existed.

Now that I've resolved that, the fix on `169_global_preferences` appears to do the trick!  It succeed on my dummy CI integration.  Thank you!  You've made a wonderful package, by the way :)   And be well, and stay safe, in these strange times.

**Comment by mmcc007** [comment]
@zbarryte-luminopia Thanks. Glad it's working for you. And keep well too!

**Comment by HakimKramdi** [comment]
Hello @zbarryte-luminopia,
How dit you get rid of the cache ?
Even with the 169_global_preferences  I still have the same issue 

regards,

**Comment by zbarryte-luminopia** [comment]
@HakimKramdi - It was long enough ago that exact recollection's been wiped from my mental cache, but IIRC, I deleted `$HOME/.pub-cache/bin/screenshots`, but I may have deleted `$HOME/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1` in addition or instead.

**Comment by davidv1992** [comment]
This error still occurs for me even on the suggested 169_global_preferences branch. I get for plutil command output the following:

```
plutil -extract AppleLocale xml1 -o - /Users/david/Library/Developer/CoreSimulator/Devices/274CBBB0-957D-4847-B322-67A12D640B8C/data/Library/Preferences/.GlobalPreferences.plist
/Users/david/Library/Developer/CoreSimulator/Devices/274CBBB0-957D-4847-B322-67A12D640B8C/data/Library/Preferences/.GlobalPreferences.plist: Could not extract value, error: No value at that key path or invalid key path: AppleLocale
```

Edit: this only seems to happen when a language was never set manually for the simulator. Workaround is to simply start simulator once, and setting a different language in the preferences.

**Comment by yahya-uddin** [comment]
I can also confirm this is still an issue. I am using v2.1.1.
The workaround I use is same as @davidv1992 , but worried about how I would do this in a CI.

**Comment by yahya-uddin** [comment]
> This error still occurs for me even on the suggested 169_global_preferences branch. I get for plutil command output the following:
> 
> ```
> plutil -extract AppleLocale xml1 -o - /Users/david/Library/Developer/CoreSimulator/Devices/274CBBB0-957D-4847-B322-67A12D640B8C/data/Library/Preferences/.GlobalPreferences.plist
> /Users/david/Library/Developer/CoreSimulator/Devices/274CBBB0-957D-4847-B322-67A12D640B8C/data/Library/Preferences/.GlobalPreferences.plist: Could not extract value, error: No value at that key path or invalid key path: AppleLocale
> ```
> 
> Edit: this only seems to happen when a language was never set manually for the simulator. Workaround is to simply start simulator once, and setting a different language in the preferences.

What do you mean by "when a language was never set manually for the simulator".

**Comment by davidv1992** [comment]
Workaround I currently use is starting the simulator once. I then go to settings/general/language & region in the simulator, and  then manually change the language there to english_us. After that, the key is present in the plist and everything works as intended.
